version: "2"
services:
  iotoi-spark-master:
    image: bde2020/spark-master:3.0.1-hadoop3.2
    container_name: spark-master
    ports:
      - "8088:8080"
      - "7077:7077"
      - "4040:4040"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - ./container-data/data:/tmp/data
      - ./container-data/scripts:/scripts
  iotoi-spark-worker-1:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - iotoi-spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://iotoi-spark-master:7077"
    volumes:
      - ./container-data/data:/tmp/data
      - ./container-data/scripts:/scripts
