version: "3.7"

services:
  iotoi-postgresql:
    image: postgres
    volumes:
      - ./container-data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
